"""Add feedback and roadmap tables

Revision ID: 0790529ca824
Revises: 99c8d3962e30
Create Date: 2025-12-08 09:55:01.186113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0790529ca824'
down_revision = '99c8d3962e30'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('BUG', 'IMPROVEMENT', name='feedbacktype'), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'IN_PROGRESS', 'RESOLVED', 'REJECTED', name='feedbackstatus'), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='feedbackpriority'), nullable=True),
    sa.Column('submitted_by', sa.String(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('submission_metadata', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedback_id'), 'feedback', ['id'], unique=False)
    op.create_index(op.f('ix_feedback_status'), 'feedback', ['status'], unique=False)
    op.create_index(op.f('ix_feedback_submitted_at'), 'feedback', ['submitted_at'], unique=False)
    op.create_index(op.f('ix_feedback_type'), 'feedback', ['type'], unique=False)
    op.create_table('roadmap_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.Enum('NEW_FEATURE', 'IMPROVEMENT', name='roadmapcategory'), nullable=False),
    sa.Column('status', sa.Enum('PLANNED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='roadmapstatus'), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('target_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('related_feedback_ids', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roadmap_items_category'), 'roadmap_items', ['category'], unique=False)
    op.create_index(op.f('ix_roadmap_items_id'), 'roadmap_items', ['id'], unique=False)
    op.create_index(op.f('ix_roadmap_items_priority'), 'roadmap_items', ['priority'], unique=False)
    op.create_index(op.f('ix_roadmap_items_status'), 'roadmap_items', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_roadmap_items_status'), table_name='roadmap_items')
    op.drop_index(op.f('ix_roadmap_items_priority'), table_name='roadmap_items')
    op.drop_index(op.f('ix_roadmap_items_id'), table_name='roadmap_items')
    op.drop_index(op.f('ix_roadmap_items_category'), table_name='roadmap_items')
    op.drop_table('roadmap_items')
    op.drop_index(op.f('ix_feedback_type'), table_name='feedback')
    op.drop_index(op.f('ix_feedback_submitted_at'), table_name='feedback')
    op.drop_index(op.f('ix_feedback_status'), table_name='feedback')
    op.drop_index(op.f('ix_feedback_id'), table_name='feedback')
    op.drop_table('feedback')
    # ### end Alembic commands ###

