"""Add IFIB scraper fields

Revision ID: 6fc9e2501bb1
Revises: 86781ca346a3
Create Date: 2025-11-29 10:25:32.695012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fc9e2501bb1'
down_revision = '86781ca346a3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('opportunities', sa.Column('eligible_organization_types', sa.Text(), nullable=True))
    op.add_column('opportunities', sa.Column('clarification_instructions', sa.Text(), nullable=True))
    op.add_column('opportunities', sa.Column('proposal_content', sa.Text(), nullable=True))
    op.add_column('opportunities', sa.Column('evaluation_criteria_full', sa.Text(), nullable=True))
    op.add_column('opportunities', sa.Column('bid_compliance_criteria', sa.Text(), nullable=True))
    op.add_column('opportunities', sa.Column('partial_bidding_allowed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('opportunities', 'partial_bidding_allowed')
    op.drop_column('opportunities', 'bid_compliance_criteria')
    op.drop_column('opportunities', 'evaluation_criteria_full')
    op.drop_column('opportunities', 'proposal_content')
    op.drop_column('opportunities', 'clarification_instructions')
    op.drop_column('opportunities', 'eligible_organization_types')
    # ### end Alembic commands ###

