"""Initial migration - Opportunity model

Revision ID: 86781ca346a3
Revises: 
Create Date: 2025-11-29 07:37:51.531112

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86781ca346a3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('opportunities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('opportunity_code', sa.String(), nullable=False),
    sa.Column('opportunity_type', sa.String(), nullable=True),
    sa.Column('nato_body', sa.String(), nullable=True),
    sa.Column('opportunity_name', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('pdf_url', sa.String(), nullable=True),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('contract_type', sa.String(), nullable=True),
    sa.Column('document_classification', sa.String(), nullable=True),
    sa.Column('response_classification', sa.String(), nullable=True),
    sa.Column('contract_duration', sa.String(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('clarification_deadline', sa.String(), nullable=True),
    sa.Column('bid_closing_date', sa.String(), nullable=True),
    sa.Column('expected_contract_award_date', sa.String(), nullable=True),
    sa.Column('bid_validity_days', sa.Integer(), nullable=True),
    sa.Column('clarification_deadline_parsed', sa.DateTime(), nullable=True),
    sa.Column('bid_closing_date_parsed', sa.DateTime(), nullable=True),
    sa.Column('expected_contract_award_date_parsed', sa.DateTime(), nullable=True),
    sa.Column('required_documents', sa.Text(), nullable=True),
    sa.Column('submission_instructions', sa.Text(), nullable=True),
    sa.Column('evaluation_criteria', sa.String(), nullable=True),
    sa.Column('contact_person', sa.String(), nullable=True),
    sa.Column('contact_email', sa.String(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_checked_at', sa.DateTime(), nullable=True),
    sa.Column('opportunity_posted_date', sa.DateTime(), nullable=True),
    sa.Column('extracted_at', sa.DateTime(), nullable=True),
    sa.Column('content_hash', sa.String(), nullable=True),
    sa.Column('last_content_update', sa.DateTime(), nullable=True),
    sa.Column('update_count', sa.Integer(), nullable=False),
    sa.Column('last_changed_fields', sa.JSON(), nullable=True),
    sa.Column('removed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_index(op.f('ix_opportunities_bid_closing_date_parsed'), 'opportunities', ['bid_closing_date_parsed'], unique=False)
    op.create_index(op.f('ix_opportunities_clarification_deadline_parsed'), 'opportunities', ['clarification_deadline_parsed'], unique=False)
    op.create_index(op.f('ix_opportunities_content_hash'), 'opportunities', ['content_hash'], unique=False)
    op.create_index(op.f('ix_opportunities_id'), 'opportunities', ['id'], unique=False)
    op.create_index(op.f('ix_opportunities_is_active'), 'opportunities', ['is_active'], unique=False)
    op.create_index(op.f('ix_opportunities_last_content_update'), 'opportunities', ['last_content_update'], unique=False)
    op.create_index(op.f('ix_opportunities_nato_body'), 'opportunities', ['nato_body'], unique=False)
    op.create_index(op.f('ix_opportunities_opportunity_code'), 'opportunities', ['opportunity_code'], unique=True)
    op.create_index(op.f('ix_opportunities_opportunity_posted_date'), 'opportunities', ['opportunity_posted_date'], unique=False)
    op.create_index(op.f('ix_opportunities_opportunity_type'), 'opportunities', ['opportunity_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_opportunities_opportunity_type'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_opportunity_posted_date'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_opportunity_code'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_nato_body'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_last_content_update'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_is_active'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_id'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_content_hash'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_clarification_deadline_parsed'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_bid_closing_date_parsed'), table_name='opportunities')
    op.drop_table('opportunities')
    # ### end Alembic commands ###

