"""add_noi_fields_estimated_value_target_issue_date_target_bid_closing_date

Revision ID: 99c8d3962e30
Revises: 65d8cb20ba20
Create Date: 2025-12-07 13:41:15.016754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99c8d3962e30'
down_revision = '65d8cb20ba20'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('opportunities', sa.Column('estimated_value', sa.String(), nullable=True))
    op.add_column('opportunities', sa.Column('target_bid_closing_date', sa.String(), nullable=True))
    op.add_column('opportunities', sa.Column('target_issue_date', sa.String(), nullable=True))
    op.add_column('opportunities', sa.Column('target_bid_closing_date_parsed', sa.DateTime(), nullable=True))
    op.add_column('opportunities', sa.Column('target_issue_date_parsed', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_opportunities_id'), 'opportunities', ['id'], unique=False)
    op.create_index(op.f('ix_opportunities_target_bid_closing_date_parsed'), 'opportunities', ['target_bid_closing_date_parsed'], unique=False)
    op.create_index(op.f('ix_opportunities_target_issue_date_parsed'), 'opportunities', ['target_issue_date_parsed'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_opportunities_target_issue_date_parsed'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_target_bid_closing_date_parsed'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_id'), table_name='opportunities')
    op.drop_column('opportunities', 'target_issue_date_parsed')
    op.drop_column('opportunities', 'target_bid_closing_date_parsed')
    op.drop_column('opportunities', 'target_issue_date')
    op.drop_column('opportunities', 'target_bid_closing_date')
    op.drop_column('opportunities', 'estimated_value')
    # ### end Alembic commands ###

